service: miranda-backend
frameworkVersion: "3"
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
    - "data/**"
    - "public/**"
provider:
  name: aws
  region: eu-west-3
  runtime: nodejs22.x
  httpApi:
    cors:
      allowedOrigins:
        - "http://hotel-dashboard-96.s3-website.eu-north-1.amazonaws.com"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: true
  environment:
    DB_CONN_STRING: ${env:DB_CONN_STRING}
    DB_NAME: ${env:DB_NAME}
functions:
  app:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY