service: miranda-backend
frameworkVersion: "3"
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
    - "data/**"
    - "public/**"
provider:
  name: aws
  region: eu-west-3
  runtime: nodejs18.x
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false
functions:
  app:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY